{
  "openapi": "3.0.2",
  "info": {
    "title": "Swagger Petstore - OpenAPI 3.0",
    "description": "This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about\nSwagger at [http://swagger.io](http://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!\nYou can now help us improve the API whether it's by making changes to the definition itself or to the code.\nThat way, with time, we can improve the API in general, and expose some of the new features in OAS3.\n\nSome useful links:\n- [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)\n- [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "email": "apiteam@swagger.io"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.19"
  },
  "externalDocs": {
    "description": "Find out more about Swagger",
    "url": "http://swagger.io"
  },
  "servers": [
    {
      "url": "/api/v3"
    }
  ],
  "tags": [
    {
      "name": "pet",
      "description": "Everything about your Pets",
      "externalDocs": {
        "description": "Find out more",
        "url": "http://swagger.io"
      }
    }
  ],
  "paths": {
    "/pet": {
      "put": {
        "tags": [
          "pet"
        ],
        "summary": "Update an existing pet",
        "description": "Update an existing pet by Id",
        "operationId": "updatePet",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of pet to return",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            },
            "examples": {
              "example-1": {
                "value": 1
              },
              "example-2": {
                "value": 2
              }
            }
          }
        ],        
        "requestBody": {
          "description": "Update an existent pet in the store",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Pet"
              },
              "examples": {
                "example-1": {
                  "summary": "Example Pet 1",
                  "value": {
                    "name": "Max",
                    "category": {
                      "id": 1,
                      "name": "Dogs"
                    },
                    "photoUrls": [
                      "http://example.com/photo1.jpg"
                    ],
                    "tags": [
                      {
                        "id": 1,
                        "name": "tag1"
                      }
                    ],
                    "status": "available"
                  }
                },
                "example-2": {
                  "summary": "Example Pet 2",
                  "value": {
                    "name": "Bella",
                    "category": {
                      "id": 2,
                      "name": "Cats"
                    },
                    "photoUrls": [
                      "http://example.com/photo2.jpg"
                    ],
                    "tags": [
                      {
                        "id": 2,
                        "name": "tag2"
                      }
                    ],
                    "status": "pending"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Pet"
                },
                "examples": {
                  "example-1": {
                    "summary": "Example Response 1",
                    "value": {
                      "id": 1,
                      "name": "Max",
                      "category": {
                        "id": 1,
                        "name": "Dogs"
                      },
                      "photoUrls": [
                        "http://example.com/photo1.jpg"
                      ],
                      "tags": [
                        {
                          "id": 1,
                          "name": "tag1"
                        }
                      ],
                      "status": "available"
                    }
                  },
                  "example-2": {
                    "summary": "Example Response 2",
                    "value": {
                      "id": 2,
                      "name": "Bella",
                      "category": {
                        "id": 2,
                        "name": "Cats"
                      },
                      "photoUrls": [
                        "http://example.com/photo2.jpg"
                      ],
                      "tags": [
                        {
                          "id": 2,
                          "name": "tag2"
                        }
                      ],
                      "status": "pending"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid ID supplied"
          },
          "404": {
            "description": "Pet not found"
          },
          "405": {
            "description": "Validation exception"
          }
        },
        "security": [
          {
            "petstore_auth": [
              "write:pets",
              "read:pets"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "pet"
        ],
        "summary": "Add a new pet to the store",
        "description": "Add a new pet to the store",
        "operationId": "addPet",
        "requestBody": {
          "description": "Create a new pet in the store",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Pet"
              },
              "examples": {
                "example-1": {
                  "summary": "Example Pet 1",
                  "value": {
                    "id": 3,
                    "name": "Charlie",
                    "category": {
                      "id": 3,
                      "name": "Birds"
                    },
                    "photoUrls": [
                      "http://example.com/photo3.jpg"
                    ],
                    "tags": [
                      {
                        "id": 3,
                        "name": "tag3"
                      }
                    ],
                    "status": "sold"
                  }
                },
                "example-2": {
                  "summary": "Example Pet 2",
                  "value": {
                    "id": 4,
                    "name": "Lucy",
                    "category": {
                      "id": 4,
                      "name": "Rabbits"
                    },
                    "photoUrls": [
                      "http://example.com/photo4.jpg"
                    ],
                    "tags": [
                      {
                        "id": 4,
                        "name": "tag4"
                      }
                    ],
                    "status": "available"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Pet"
                },
                "examples": {
                  "example-1": {
                    "summary": "Example Response 1",
                    "value": {
                      "id": 3,
                      "name": "Charlie",
                      "category": {
                        "id": 3,
                        "name": "Birds"
                      },
                      "photoUrls": [
                        "http://example.com/photo3.jpg"
                      ],
                      "tags": [
                        {
                          "id": 3,
                          "name": "tag3"
                        }
                      ],
                      "status": "sold"
                    }
                  },
                  "example-2": {
                    "summary": "Example Response 2",
                    "value": {
                      "id": 4,
                      "name": "Lucy",
                      "category": {
                        "id": 4,
                        "name": "Rabbits"
                      },
                      "photoUrls": [
                        "http://example.com/photo4.jpg"
                      ],
                      "tags": [
                        {
                          "id": 4,
                          "name": "tag4"
                        }
                      ],
                      "status": "available"
                    }
                  }
                }
              }
            }
          },
          "405": {
            "description": "Invalid input"
          }
        },
        "security": [
          {
            "petstore_auth": [
              "write:pets",
              "read:pets"
            ]
          }
        ]
      }
    },
    "/pet/{petId}": {
      "get": {
        "tags": [
          "pet"
        ],
        "summary": "Find pet by ID",
        "description": "Returns a single pet",
        "operationId": "getPetById",
        "parameters": [
          {
            "name": "petId",
            "in": "path",
            "description": "ID of pet to return",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            },
            "examples": {
              "example-1": {
                "value": 1
              },
              "example-2": {
                "value": 2
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Pet"
                },
                "examples": {
                  "example-1": {
                    "summary": "Example Response 1",
                    "value": {
                      "id": 1,
                      "name": "Max",
                      "category": {
                        "id": 1,
                        "name": "Dogs"
                      },
                      "photoUrls": [
                        "http://example.com/photo1.jpg"
                      ],
                      "tags": [
                        {
                          "id": 1,
                          "name": "tag1"
                        }
                      ],
                      "status": "available"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid ID supplied",
            "content": {
              "application/json": {
                "examples": {
                  "example-2": {
                    "summary": "Example error",
                    "value": {
                       "error": {
                        "message": "invalid id 2"
                       }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Pet not found"
          }
        },
        "security": [
          {
            "api_key": []
          },
          {
            "petstore_auth": [
              "write:pets",
              "read:pets"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "Order": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "example": 10
          },
          "petId": {
            "type": "integer",
            "format": "int64",
            "example": 198772
          },
          "quantity": {
            "type": "integer",
            "format": "int32",
            "example": 7
          },
          "shipDate": {
            "type": "string",
            "format": "date-time"
          },
          "status": {
            "type": "string",
            "description": "Order Status",
            "example": "approved",
            "enum": [
              "placed",
              "approved",
              "delivered"
            ]
          },
          "complete": {
            "type": "boolean"
          }
        }
      },
      "Customer": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "example": 100000
          },
          "username": {
            "type": "string",
            "example": "fehguy"
          },
          "address": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Address"
            }
          }
        }
      },
      "Address": {
        "type": "object",
        "properties": {
          "street": {
            "type": "string",
            "example": "437 Lytton"
          },
          "city": {
            "type": "string",
            "example": "Palo Alto"
          },
          "state": {
            "type": "string",
            "example": "CA"
          },
          "zip": {
            "type": "string",
            "example": "94301"
          }
        }
      },
      "Category": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "example": 1
          },
          "name": {
            "type": "string",
            "example": "Dogs"
          }
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "example": 10
          },
          "username": {
            "type": "string",
            "example": "theUser"
          },
          "firstName": {
            "type": "string",
            "example": "John"
          },
          "lastName": {
            "type": "string",
            "example": "James"
          },
          "email": {
            "type": "string",
            "example": "john@email.com"
          },
          "password": {
            "type": "string",
            "example": "12345"
          },
          "phone": {
            "type": "string",
            "example": "12345"
          },
          "userStatus": {
            "type": "integer",
            "description": "User Status",
            "format": "int32",
            "example": 1
          }
        }
      },
      "Tag": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "Pet": {
        "required": [
          "name",
          "photoUrls"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "example": 10
          },
          "name": {
            "type": "string",
            "example": "doggie"
          },
          "category": {
            "$ref": "#/components/schemas/Category"
          },
          "photoUrls": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "tags": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Tag"
            }
          },
          "status": {
            "type": "string",
            "description": "pet status in the store",
            "enum": [
              "available",
              "pending",
              "sold"
            ]
          }
        }
      },
      "ApiResponse": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32"
          },
          "type": {
            "type": "string"
          },
          "message": {
            "type": "string"
          }
        }
      }
    },
    "requestBodies": {
      "Pet": {
        "description": "Pet object that needs to be added to the store",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Pet"
            }
          }
        }
      },
      "UserArray": {
        "description": "List of user object",
        "content": {
          "application/json": {
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/User"
              }
            }
          }
        }
      }
    },
    "securitySchemes": {
      "petstore_auth": {
        "type": "oauth2",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://petstore3.swagger.io/oauth/authorize",
            "scopes": {
              "write:pets": "modify pets in your account",
              "read:pets": "read your pets"
            }
          }
        }
      },
      "api_key": {
        "type": "apiKey",
        "name": "api_key",
        "in": "header"
      }
    }
  }
}